fullName = "Amrutha varshini";
price = 12.99;
x = null;
y = undefined;
age = 20;
isFollow = true;
isOrdered = false;
fullName = "Ammu";
console.log(fullName);
console.log(typeof fullName);
console.log(price);
console.log(typeof price);
console.log(x);
console.log(typeof x);
console.log(y);
console.log(typeof y);
console.log(isFollow);
console.log(typeof isFollow);
console.log(isOrdered);
console.log(typeof isOrdered);
console.log(age);
console.log(typeof age);
